import { relations } from "drizzle-orm"
import { index, int, integer, sqliteTable, text, unique } from "drizzle-orm/sqlite-core"

/**
 * Bitwise role flags for user access control.
 * Roles are additive — a single user can hold multiple roles by combining flags.
 * Use {@link hasRole} to test role membership.
 *
 * @example
 * // Supervisor + Admin combined
 * const role = Role.Supervisor | Role.Admin // 6
 * hasRole(role, Role.Admin) // true
 */
export const Role = {
	/** Students can view and edit risk assessments for their active team. */
	Student: 1,
	/** Supervisors manage team members, leave feedback, and view team audit trails. */
	Supervisor: 2,
	/** Admins have full access — users, teams, semesters, and all audits. */
	Admin: 4,
} as const

/** Union type of valid role flag values (1, 2, or 4). */
export type RoleFlag = (typeof Role)[keyof typeof Role]

/**
 * Tests whether a user's role bitmask includes the given flag.
 *
 * @param userRole - The integer bitmask stored in `users.role`.
 * @param flag - A {@link Role} constant to test for.
 * @returns `true` if the user holds the specified role flag.
 *
 * @example
 * hasRole(6, Role.Supervisor) // true  (6 = Supervisor | Admin)
 * hasRole(1, Role.Admin)      // false
 */
export function hasRole(userRole: number, flag: number): boolean {
	return (userRole & flag) !== 0
}

const auditCols = {
	createdBy: text("created_by").notNull(),
	createdDate: text("created_date")
		.notNull()
		.$defaultFn(() => new Date().toISOString()),
	modifiedBy: text("modified_by").notNull(),
	modifiedDate: text("modified_date")
		.notNull()
		.$defaultFn(() => new Date().toISOString()),
	deletedAt: text("deleted_at"),
	deletedBy: text("deleted_by"),
}

/**
 * Application user accounts.
 * Admins pre-create accounts with just a name and email, then generate a one-time
 * invite link. Following the link lets the user set their password, which populates
 * {@link users.passwordHash} and clears the invite columns.
 */
export const users = sqliteTable("users", {
	/** Internal UUID generated by the application. */
	id: text("id").primaryKey(),
	fullName: text("full_name").notNull(),
	email: text("email").notNull().unique(),
	studentId: text("student_id"),
	/** Bitwise role flags. Use {@link hasRole} to test membership. Defaults to Student (1). */
	role: integer("role").notNull().default(Role.Student),
	/** scrypt hash in `scrypt$N$r$p$salt$hash` format. Null until the user sets a password. */
	passwordHash: text("password_hash"),
	/** SHA-256 of the outstanding invite token. Null when no invite is live. */
	inviteTokenHash: text("invite_token_hash"),
	/** ISO timestamp after which the outstanding invite is no longer valid. */
	inviteTokenExpiresAt: text("invite_token_expires_at"),
	...auditCols,
})

/**
 * Server-side login sessions. The browser cookie holds a random opaque token;
 * this table stores only its SHA-256 hash. Deleting a row revokes the session.
 * Like {@link audits}, sessions are infrastructure — no audit columns.
 */
export const sessions = sqliteTable(
	"sessions",
	{
		/** SHA-256 hash of the raw session token (the raw token lives only in the cookie). */
		id: text("id").primaryKey(),
		userId: text("user_id")
			.notNull()
			.references(() => users.id, { onDelete: "cascade" }),
		expiresAt: text("expires_at").notNull(),
		createdAt: text("created_at")
			.notNull()
			.$defaultFn(() => new Date().toISOString()),
	},
	(t) => [index("sessions_user_id_idx").on(t.userId)],
)

/**
 * Academic semesters that group teams and control their active state.
 * When a semester is inactive, all child assessments become read-only
 * and students on those teams cannot sign in.
 */
export const semesters = sqliteTable("semesters", {
	id: int("id").primaryKey({ autoIncrement: true }),
	name: text("name").notNull(),
	year: integer("year").notNull(),
	period: text("period", { enum: ["1", "2", "summer"] }).notNull(),
	startDate: text("start_date").notNull(),
	endDate: text("end_date").notNull(),
	/** Controls whether associated teams and assessments are read-only. Defaults to true. */
	isActive: integer("is_active", { mode: "boolean" }).notNull().default(true),
	...auditCols,
})

/** Project teams belonging to a semester. Active state is derived from the linked semester. */
export const teams = sqliteTable("teams", {
	id: int("id").primaryKey({ autoIncrement: true }),
	name: text("name").notNull(),
	semesterId: int("semester_id")
		.notNull()
		.references(() => semesters.id, { onDelete: "restrict" }),
	...auditCols,
})

/** Membership records linking users to teams with a student or supervisor role. */
export const teamMembers = sqliteTable(
	"team_members",
	{
		teamId: int("team_id")
			.notNull()
			.references(() => teams.id, { onDelete: "cascade" }),
		userId: text("user_id")
			.notNull()
			.references(() => users.id, { onDelete: "cascade" }),
		memberRole: text("member_role", { enum: ["student", "supervisor"] }).notNull(),
		...auditCols,
	},
	(t) => [
		unique("team_member_unique").on(t.teamId, t.userId),
		index("team_members_user_id_idx").on(t.userId),
	],
)

/** Risk assessments created by a team, aligned with ISO 27001, SOC 2, or both. */
export const assessments = sqliteTable(
	"assessments",
	{
		id: int("id").primaryKey({ autoIncrement: true }),
		teamId: int("team_id")
			.notNull()
			.references(() => teams.id, { onDelete: "cascade" }),
		title: text("title").notNull(),
		framework: text("framework", { enum: ["ISO27001", "SOC2", "BOTH"] })
			.notNull()
			.default("ISO27001"),
		status: text("status", { enum: ["draft", "submitted", "reviewed", "approved"] })
			.notNull()
			.default("draft"),
		...auditCols,
	},
	(t) => [index("assessments_team_id_idx").on(t.teamId)],
)

/** Individual risk entries within an assessment following the ISO 27001 risk model. */
export const riskItems = sqliteTable(
	"risk_items",
	{
		id: int("id").primaryKey({ autoIncrement: true }),
		assessmentId: int("assessment_id")
			.notNull()
			.references(() => assessments.id, { onDelete: "cascade" }),
		assetName: text("asset_name").notNull(),
		assetCategory: text("asset_category").notNull(),
		threat: text("threat").notNull(),
		vulnerability: text("vulnerability").notNull(),
		/** Likelihood rating 1–5. Combined with {@link riskItems.impact} to compute {@link riskItems.riskScore}. */
		likelihood: integer("likelihood").notNull(),
		/** Impact rating 1–5. Combined with {@link riskItems.likelihood} to compute {@link riskItems.riskScore}. */
		impact: integer("impact").notNull(),
		/** Stored risk score = likelihood × impact (1–25). Stored for efficient DataTable sorting. */
		riskScore: integer("risk_score").notNull(),
		treatment: text("treatment", { enum: ["accept", "mitigate", "transfer", "avoid"] }).notNull(),
		controls: text("controls"),
		residualRisk: integer("residual_risk"),
		soc2Criteria: text("soc2_criteria"),
		...auditCols,
	},
	(t) => [index("risk_items_assessment_id_idx").on(t.assessmentId)],
)

/** Supervisor comments on a risk assessment. */
export const feedback = sqliteTable(
	"feedback",
	{
		id: int("id").primaryKey({ autoIncrement: true }),
		assessmentId: int("assessment_id")
			.notNull()
			.references(() => assessments.id, { onDelete: "cascade" }),
		supervisorId: text("supervisor_id")
			.notNull()
			.references(() => users.id),
		comment: text("comment").notNull(),
		...auditCols,
	},
	(t) => [index("feedback_assessment_id_idx").on(t.assessmentId)],
)

/**
 * Append-only audit log tracking all entity changes application-wide.
 * Rows are immutable — no `modifiedBy`, `modifiedDate`, `deletedAt`, or `deletedBy` columns.
 */
export const audits = sqliteTable("audits", {
	id: int("id").primaryKey({ autoIncrement: true }),
	entityType: text("entity_type", {
		enum: ["user", "team", "semester", "assessment", "risk_item", "feedback"],
	}).notNull(),
	entityId: text("entity_id").notNull(),
	action: text("action", { enum: ["created", "updated", "deleted"] }).notNull(),
	/** Name of the field that changed, if this is an "updated" entry. */
	fieldChanged: text("field_changed"),
	oldValue: text("old_value"),
	newValue: text("new_value"),
	createdBy: text("created_by").notNull(),
	createdDate: text("created_date")
		.notNull()
		.$defaultFn(() => new Date().toISOString()),
})

// ─── Relations ────────────────────────────────────────────────────────────────
export const usersRelations = relations(users, ({ many }) => ({
	teamMemberships: many(teamMembers),
	feedbackGiven: many(feedback),
	sessions: many(sessions),
}))

export const sessionsRelations = relations(sessions, ({ one }) => ({
	user: one(users, { fields: [sessions.userId], references: [users.id] }),
}))

export const semestersRelations = relations(semesters, ({ many }) => ({
	teams: many(teams),
}))

export const teamsRelations = relations(teams, ({ one, many }) => ({
	semester: one(semesters, { fields: [teams.semesterId], references: [semesters.id] }),
	members: many(teamMembers),
	assessments: many(assessments),
}))

export const teamMembersRelations = relations(teamMembers, ({ one }) => ({
	team: one(teams, { fields: [teamMembers.teamId], references: [teams.id] }),
	user: one(users, { fields: [teamMembers.userId], references: [users.id] }),
}))

export const assessmentsRelations = relations(assessments, ({ one, many }) => ({
	team: one(teams, { fields: [assessments.teamId], references: [teams.id] }),
	riskItems: many(riskItems),
	feedback: many(feedback),
}))

export const riskItemsRelations = relations(riskItems, ({ one }) => ({
	assessment: one(assessments, { fields: [riskItems.assessmentId], references: [assessments.id] }),
}))

export const feedbackRelations = relations(feedback, ({ one }) => ({
	assessment: one(assessments, { fields: [feedback.assessmentId], references: [assessments.id] }),
	supervisor: one(users, { fields: [feedback.supervisorId], references: [users.id] }),
}))

// ─── Inferred Types ───────────────────────────────────────────────────────────

/** Selected row shape for the users table. */
export type User = typeof users.$inferSelect
/** Insert shape for the users table. */
export type NewUser = typeof users.$inferInsert
/** Selected row shape for the semesters table. */
export type Semester = typeof semesters.$inferSelect
/** Insert shape for the semesters table. */
export type NewSemester = typeof semesters.$inferInsert
/** Selected row shape for the teams table. */
export type Team = typeof teams.$inferSelect
/** Insert shape for the teams table. */
export type NewTeam = typeof teams.$inferInsert
/** Selected row shape for the team_members table. */
export type TeamMember = typeof teamMembers.$inferSelect
/** Selected row shape for the assessments table. */
export type Assessment = typeof assessments.$inferSelect
/** Insert shape for the assessments table. */
export type NewAssessment = typeof assessments.$inferInsert
/** Selected row shape for the risk_items table. */
export type RiskItem = typeof riskItems.$inferSelect
/** Insert shape for the risk_items table. */
export type NewRiskItem = typeof riskItems.$inferInsert
/** Selected row shape for the feedback table. */
export type Feedback = typeof feedback.$inferSelect
/** Insert shape for the feedback table. */
export type NewFeedback = typeof feedback.$inferInsert
/** Selected row shape for the audits table. */
export type Audit = typeof audits.$inferSelect
/** Selected row shape for the sessions table. */
export type Session = typeof sessions.$inferSelect
/** Insert shape for the sessions table. */
export type NewSession = typeof sessions.$inferInsert
